#!/bin/bash

docker build -t ipogudin/cloudera-cluster-node ./cloudera-cluster-node/
docker build -t ipogudin/cloudera-cluster-hadoop-node ./cloudera-cluster-hadoop-node/
docker build -t ipogudin/cloudera-cluster-hbase-node ./cloudera-cluster-hbase-node/